version: '3'
services:
  db-kuber-test:
    image: postgres:12
    restart: always
    ports:
      - 5550:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: kuber-test